on:
  push:
    branches:
      - master 





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username mostafazahra --password dckr_pat_qD4pkiKquCRVbMOkLreK0DkcW3Q